### ISSUE TITLE
Segfault when exiting to menu

### ISSUE THREAD

**Issue by AI-WAIFU** [EleutherAI/minetest#37]
A segfault occurs if a user joins or starts a game and then tries to exit back to the menu.

**Comment by rk1a** [comment]
Does this also occur when passing `--go`, i.e. skipping the menu?

**Comment by rk1a** [comment]
see https://discord.com/channels/729741769192767510/1014999314835181650/1079182307711270932

**Comment by AI-WAIFU** [comment]
Fixed as part of  #53
