### ISSUE TITLE
translator: gpt-neox

### ISSUE THREAD

**Issue by Pantyhose-X** [EleutherAI/minetest#39]
Write a [gpt-neox](https://github.com/EleutherAI/gpt-neox) and [Apertium](https://github.com/apertium) script to automatically check the relevant strings, translate them and write them to the locale.

local S = minetest.get_translator
local S = minetest.get_translator(minetest.get_current_modname())
description = 
description = S

**Comment by AI-WAIFU** [comment]
This is probably a bit out of scope, maybe more appropriate for the actual minetest project
